### ISSUE TITLE
Domoticz v2023.1

### ISSUE THREAD

**Issue by CHolivier** [akamming/homebridge-domoticz-thermostat#1] opened 2023-03-29 15:58 UTC
Hi
Since the latest update from domoticz, this (amazing) plug-in doesn't work anymore.
In the logs I keep getting this error: 
Error: Domoticz returned statuscode 401
[29/03/2023, 17:44:55] [XXXXXX] invalid reponse code: 401, on http://127.0.0.1:8080/json.htm?type=devices&rid=106

Any ideas how to fix this?
I can parse json commands with other scripts without problems.
Kind regards

**Comment by akamming** [comment] 2023-03-29 18:57
that's weird... i don't know. And i can't test. I havent upgraded my own system to domoticz 2023.1 yet. 

I know it has enhanced security and that extra layer needs to be configured to prevent abuse, so my guess would be: Check the [security setup](https://github.com/domoticz/domoticz/blob/development/SECURITY_SETUP.md) ?

**Comment by kristoferw** [comment] 2023-05-02 12:20
Same problem here.
It doesn’t help to enable Basic auth API access either.

**Comment by CHolivier** [comment] 2023-05-02 16:40
Hello @akamming 
Thanks for the answer. I tried to fiddle around the security setup but I wasn't able to find a workaround.

**Comment by akamming** [comment] 2023-06-14 18:54
Just did the upgrade to 2023.1 myself. Have 2 pi's with domoticz, so tested on both of them. Unfortunately i was unable to reproduce the behaviour.  so i cannot troubleshoot.. sorry..

**Comment by akamming** [comment] 2023-06-14 18:56
only extra workaround i can think of is to add the ip of your homebridge in the trusted networks ...

**Comment by GravityRZ** [comment] 2023-08-15 14:09
i also experienced this
2023.1(15092) was working fine but 2023.2(15503) not

in 2023.2 old api call generate a warning in domoticz regarding depreciated code
it seems you need to change the code

/json.htm?type=devices&rid=IDX
into
 /json.htm?type=command&param=getdevices&rid=IDX

i am not sure this fixes the error in homebridge thermostat but i think it does.
at least it should fix the warning in domoticz so either way it is good to change it to the latest standard

i tried this however with the 2023.1 version and this gives an error

it looks like the current plugin works with the 2023.1 version but if you change it into the new format it will work with 2023.2 BUT WILL BREAK WHEN YOU STILL USE THE 2023.1 VERSION OF DOMOTICZ

maybe it is smart to make a new version where the command to be used can be specified by the user

something like
Domoticz command used to read out device:/json.htm?type=command&param=getdevices&rid=


@akamming  please look at this
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's

**Comment by akamming** [comment] 2023-08-15 17:39
I know i have to update to new Json. But still works in 2023.2 (i am on that version with no issues) pls describe the issue you have. It mist be something else or inwippen have had the Same issue

**Comment by GravityRZ** [comment] 2023-08-15 17:45
well it gives an error when it tries to communicate with domoticz.
this is what i see in the log

invalid reponse code: 401, on http://192.168.1.50:8084/json.htm?type=devices&rid=378
i tried to change things regarding security but it did not help. also clearing cache and restarting homebridge did not help

![image](https://github.com/akamming/homebridge-domoticz-thermostat/assets/16853535/4a54dbed-551f-484c-b3e0-86935e35bb77)

**Comment by GravityRZ** [comment] 2023-08-15 17:46
i have it running in docker on the same host(synology) as the other containers like homebridge

**Comment by akamming** [comment] 2023-08-15 20:37
401 means unauthorized.

that’s weird in my setup works fine…

Did you allow basic auth authentication over http in your domoticz settings?

alternatively you could add the ip of your docker container to the trusted Network adresses in domoticz…

**Comment by GravityRZ** [comment] 2023-08-16 13:31
i tried the following
with 2023.1 working (basic authentification OFF)

i enabled basic authentification in domoticz
stop domoticz
start domoticz
stop homebridge
start homebridge

i now get the same 401 Error

so with basic auth OFF everything working
with basic auth ON  401 error

i did some more testing
normally the username and password is blank in the thermostat plugin.
this creates an error when on basic authorization
i created a user in domoticz(ronald:ronald)
i filled these credentials into the plugin
restarted homebridge and everything working
also it works regardless if basic auth is on or not.

not sure if it also works in the 2023.2 version but this looks promising.

i thought the user and password were not mandatory but i think you should update the readme to make it mandatory

in case this solves the working issue we still have the depreciated warning in domoticz when switching to 2023.2 because of the old json format used by the plugin







with domoticz 2023.2 it was not working in the first place (basic auth OFF) and also enabling it did not help

**Comment by GravityRZ** [comment] 2023-08-16 15:03
more tests

i upgraded to 15503(2023.2)

with the user changes in place and without basic auth on 
Error 401

with the user changes in place and WITH basic auth on 
Everything working

so it seems they upgraded the security and the plugin can only work with a valid user AND with basic auth on

**Comment by GravityRZ** [comment] 2023-08-16 15:28
can you also check how the plugin sends out the username and password
NOTE: API URLs with username and password as parameters (eg https://IP:PORT/json.htm?username=userBASE64&password=PWDBASE64& ) are not supported anymore!

if you do not need a username password when everything is in the trusted network i suspect there is something wrong with the plugin.

with domoticz 15092(2023.1) and plugin without user:password(left blank)
basic auth off: no error everything working
basic auth on:error 401

with domoticz 15092(2023.1) and plugin WITH user:password(ronald:ronald)
basic auth off: no error everything working
basic auth on:no error everything working

with domoticz 15503(2023.2) and plugin without user:password(left blank)
basic auth off: error 401
basic auth on:error 401

with domoticz 15503(2023.2) and plugin WITH user:password(ronald:ronald)
basic auth off: error 401
basic auth on:no errors everything working


so somehow the new domoticz can not handle it when no user:password is specified
it can be that there still is a bug in the plugin
it could also be that the security in 2023.1 was not funcioning properly ang now in 2023.2 they fixed it.

then it is still strange that the trusted network setting should be used but aparently it is not using it

**Comment by CHolivier** [comment] 2023-08-16 19:12
Hello @GravityRZ and @akamming 
I was able to fix the issue by creating a user + password and adding the credentials into homebridge config. Basic auth is enabled and Im running domoticz v. 2023.2 (19efd039c).
Kind regards.

**Comment by GravityRZ** [comment] 2023-08-16 19:36
> Hello @GravityRZ and @akamming I was able to fix the issue by creating a user + password and adding the credentials into homebridge config. Basic auth is enabled and Im running domoticz v. 2023.2 (19efd039c). Kind regards.

yes that is exactly what i did also to fix it.

still it is strange that when no user/password is provided domoticz should use the trusted network.
somehow domoticz still thinks credentials are passed(which are wrong) thus creating the 401 error
Or this functionaly should not have worked in the past but it slipped through because domoticz security wwas not that strict.
now that it is it is not accepted anymore.

**Comment by akamming** [comment] 2023-08-16 19:45
The diff with my setup
Is that i indeed always use a user/Pw combi. Never trusted without authentication. That’s a setup i would not recommend to Antoine

Currently on holiday. But I will take a look when I’m back (will take Some time)

Tx for all the testing and investigation

**Comment by GravityRZ** [comment] 2023-08-16 20:12
no problem. enjoy your holiday.

**Comment by akamming** [comment] 2023-08-17 05:38
Just checked the domoticz docs

In the security docs it States that as of 2023.1 Having at least 1 (admin) user is mandatory

So then you also indeed need an authorized api call as of 2023.1 unless you specify a trusted ip adress in the config

This is according to the behaviour you describe. So this cannot be fixed in the code and i will update the documentation after my holiday

**Comment by akamming** [comment] 2023-08-23 18:27
release version 0.2.0 and updated docs. Issue closed

**Closed as completed by akamming** 2023-08-23 18:27 UTC

**Comment by GravityRZ** [comment] 2023-08-23 20:21
will test tomorrow but looking at the code this should work.
will also see what it does when username:passwd is left blank again(it should use the trusted network but looking at previous experience we probably need to use user:passwd and basic auth)

**Comment by akamming** [comment] 2023-08-23 21:11
Empty username/pwd should not work as per api docs. So i did not test. It might work, bit security wise it’s an untecommended situation anyway…

**Comment by GravityRZ** [comment] 2023-08-24 11:59
tested it
works with username:password, does not work without

HOWEVER
to make sure i removed the cached homebridge info and let it discover every device again
the thermostat stopped working(strange)
i decided to remove the plugin and add it again. (hint search for domoticz because when you search Thermostat it will not show up)

now everything working again.

**Comment by akamming** [comment] 2023-08-24 14:12
no idea what can be causing that. For that you would need to share the logs first...  (both from installation of the plugin as well as the normal logs when in operation)

**Comment by GravityRZ** [comment] 2023-08-24 14:17
yeh, i will leave it at that.
the problem only appeared when i reset homebridge and reinstalling the plugin solved it so i think we are good to go.

turned out homebridge itself was using deprecciated code.
tey fixed in 2 months ago with a new domoticz.js but somehow this is not pulled when installing using npm (i think homebridge uses this) 
also i manually replaced the file in the container and no more depreciated messages from homebridge

**Comment by domoticauser** [comment] 2023-08-28 18:50
How to do that? 
 "also i manually replaced the file in the container and no more depreciated messages from homebridge"

 [WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command!

**Comment by akamming** [comment] 2023-08-28 19:08
Correct api command is in last version. So pls upgrade to latest version

**Comment by GravityRZ** [comment] 2023-08-28 19:14
> How to do that? "also i manually replaced the file in the container and no more depreciated messages from homebridge"
> 
> [WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command!

i mentioned that in regards to the edomoticz plugin which has the same problem.

to get rid of the depreciated warning CAUSED by the THERMOSTAT plugin: like akamming said, update the plugin

to get rid of the depreciated warning CAUSED by the eDOMOTICZ plugin: look at this link

https://github.com/PatchworkBoy/homebridge-edomoticz/issues/265
